name: twitterbot
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  flipdot-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.0.0
      - run: python -m pip install -r requirements.txt 
      - name: Fetch current xls
        run: python fetch_api.py
      - name: Create and post tweet
        run: python postTweet.py
